name: Build Outfit Converter Pro

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master ]
  release:
    types: [ created ]

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.5.0'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_msvc2019_64'
        modules: 'qtbase'
        cache: true
        
    - name: Setup MSVC
      uses: ilammy/msvc-dev-cmd@v1
      
    - name: Configure CMake
      run: cmake -B build -DCMAKE_BUILD_TYPE=Release
      
    - name: Build
      run: cmake --build build --config Release
      
    - name: Package
      run: |
        mkdir package
        copy build\bin\Release\OutfitConverterPro.exe package\
        cd package
        windeployqt OutfitConverterPro.exe
        
    - name: Upload Windows Artifact
      uses: actions/upload-artifact@v3
      with:
        name: OutfitConverterPro-Windows
        path: package/
        
  build-macos:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.5.0'
        host: 'mac'
        target: 'desktop'
        modules: 'qtbase'
        cache: true
        
    - name: Configure CMake
      run: cmake -B build -DCMAKE_BUILD_TYPE=Release
      
    - name: Build
      run: cmake --build build --config Release
      
    - name: Create DMG
      run: |
        cd build/bin
        macdeployqt OutfitConverterPro.app -dmg
        
    - name: Upload macOS Artifact
      uses: actions/upload-artifact@v3
      with:
        name: OutfitConverterPro-macOS
        path: build/bin/OutfitConverterPro.dmg
        
  build-linux:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake ninja-build
        
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.5.0'
        host: 'linux'
        target: 'desktop'
        modules: 'qtbase'
        cache: true
        
    - name: Configure CMake
      run: cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Release
      
    - name: Build
      run: cmake --build build
      
    - name: Create AppImage
      run: |
        wget -c -nv "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
        chmod a+x linuxdeployqt-continuous-x86_64.AppImage
        mkdir -p AppDir/usr/bin
        cp build/bin/OutfitConverterPro AppDir/usr/bin/
        ./linuxdeployqt-continuous-x86_64.AppImage AppDir/usr/bin/OutfitConverterPro -appimage
        
    - name: Upload Linux Artifact
      uses: actions/upload-artifact@v3
      with:
        name: OutfitConverterPro-Linux
        path: Outfit_Converter_Pro*.AppImage
        
  release:
    needs: [build-windows, build-macos, build-linux]
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v3
      
    - name: Create release archives
      run: |
        cd OutfitConverterPro-Windows
        zip -r ../OutfitConverterPro-Windows.zip *
        cd ../OutfitConverterPro-macOS
        zip -r ../OutfitConverterPro-macOS.zip *
        cd ../OutfitConverterPro-Linux
        zip -r ../OutfitConverterPro-Linux.zip *
        
    - name: Upload to Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          OutfitConverterPro-Windows.zip
          OutfitConverterPro-macOS.zip
          OutfitConverterPro-Linux.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
